import pandas as pd
import matplotlib.pyplot as plt

Dna_seq="""
ATGTCCAAACCCAGCGACCACATCAAGCGCCCCATGAACGCCTTCATGGT
GTGGTCCCGCGGCCAGCGGCGCAAGATGGCCCAGGAGAACCCCAAAATGCACAACTCGGAAATCAGCAAG
CGGCTGGGCGCGGAGTGGAAGCTGCTCTCCGAGGCGGAGAAGCGGCCCTACATCGACGAG
GCCAAGCGGCTGCGGGCGCAACACATGAAGGAACACCCCGACTACAAGTACCGGCCCCGG
CGCAAGCCCAAGAACCTGCTCAAAAAGGACAGGTATGTCTTCCCTTTGCCTTACCTGGGG
GAAACCGATCCCTTAAAGGCTGCCGGGCTTCCCGTGGGGGCCACTGACTCGCTGCTGAGC
TCCCCGGAGAAGGCCAGGGCTTTCCTGCCCCCCACCTCAGCACCTTACTCCTTACTTGAC
CCCAGCCAGTTCAGCTCCAGCGCCATTCAGAAGATGACCGAGGTTCCTCACACCTTGGCC
ACCGGCACCCTGCCCTACGCCTCCACCTTGGGATACCAGAACGGGGCGTTCGGCAGCCTG
AGCTGCCCCAGCCAACACACCCACACCCACCCCTCGCCGACCAACCCGGGCTACGTGGTG
CCGTGTAACTGTACCGCTTGGTCGGCCTCCAGTTTGCAGCCTCCGGTTGCCTACATATTA
TTCCCGGGCATGACCAAGACTGGCATAGACCCCTATTCTTCAGCACACGCGACTGCTATG
TAA
"""

# now lets analyze data using pandas

dna_series=pd.Series(list(Dna_seq))  #this is the way to show your seq in list
# print(dna_series)

# now lets count each base

counts=dna_series.value_counts()
print(counts)


# now lets show a graph using matplotlib

counts.plot(kind="bar" , color=["green","blue","purple","red"])
plt.title("DNA Base Counts")
plt.xlabel("A/T/G/C")
plt.ylabel("Frequencey")
plt.show()
